databases:
  - name: iniad-monsters
    plan: free
    databaseName: iniad-monsters
    user: iniad-user

services:
  - type: web
    name: INI'MON
    env: python
    region: singapore
    plan: free
    branch: production
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.2
      - key: DATABASE_URL
        fromDatabase:
          name: iniad-monsters
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: config.production
      - key: WEB_CONCURRENCY
        value: 4